include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    avoid_print: true
    prefer_single_quotes: true
    always_use_package_imports: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    prefer_typing_uninitialized_variables: true
    use_key_in_widget_constructors: true 