// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD0l6ZS-9ayZDE5RLzzmtytNKtLTlN8lk',
    appId: '1:377376225464:web:9db1a5bed032bf6ee95c4d',
    messagingSenderId: '377376225464',
    projectId: 'siba-a8e24',
    authDomain: 'siba-a8e24.firebaseapp.com',
    storageBucket: 'siba-a8e24.firebasestorage.app',
    measurementId: 'G-ZZ4EHVRSNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAREgWNuiwCYP-YD788QYFOjYRvJFuh9VA',
    appId: '1:377376225464:android:e9d9db96f781a660e95c4d',
    messagingSenderId: '377376225464',
    projectId: 'siba-a8e24',
    storageBucket: 'siba-a8e24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCczktmkLJkblS1tFltlB7ao-JDm_cAqg8',
    appId: '1:377376225464:ios:8ef793b9fae5fc05e95c4d',
    messagingSenderId: '377376225464',
    projectId: 'siba-a8e24',
    storageBucket: 'siba-a8e24.firebasestorage.app',
    iosBundleId: 'com.example.s',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD0l6ZS-9ayZDE5RLzzmtytNKtLTlN8lk',
    appId: '1:377376225464:web:000b361c66292636e95c4d',
    messagingSenderId: '377376225464',
    projectId: 'siba-a8e24',
    authDomain: 'siba-a8e24.firebaseapp.com',
    storageBucket: 'siba-a8e24.firebasestorage.app',
    measurementId: 'G-B7W53M6Y22',
  );

}